const getters = {
  sidebar: state => state.app.sidebar,
  size: state => state.app.size,
  device: state => state.app.device,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  permission_routes: state => state.permission.routes,
  // common
  systems: state => state.common.systems,
  projects: state => state.common.projects,
  group_users: state => state.common.group_users,
  all_group_users: state => state.common.all_group_users,
  // user
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  user_id: state => state.user.user_id,
  user_mail_days: state => state.user.user_mail_days,
  name: state => state.user.name,
  username: state => state.user.username,
  email: state => state.user.email,
  slims_name: state => state.user.slims_name,
  group: state => state.user.group,
  organization: state => state.user.organization,
  roles: state => state.user.roles,
  // check out list
  checkout_table: state => state.checkouts.checkout_table,
  checkout_current_page: state => state.checkouts.checkout_current_page,
  checkout_page_size: state => state.checkouts.checkout_page_size,
  checkout_page_count: state => state.checkouts.checkout_page_count,
  checkout_count: state => state.checkouts.checkout_count,
  // work bench
  task_bar: state => state.workbench.task_bar,
  project_items: state => state.workbench.project_items,
  slip_no_items: state => state.workbench.slip_no_items,
  slip_current_page: state => state.workbench.slip_current_page,
  slip_page_size: state => state.workbench.slip_page_size,
  slip_page_count: state => state.workbench.slip_page_count,
  slip_count: state => state.workbench.slip_count,
  slip_table: state => state.workbench.slip_table,
  task_test_mcl: state => state.workbench.task_test_mcl,
  task_test_pcl: state => state.workbench.task_test_pcl,
  task_approval: state => state.workbench.task_approval,
  task_confirm: state => state.workbench.task_confirm,
  task_release: state => state.workbench.task_release,
  // project
  project_mcl_list: state => state.projects.project_mcl_list,
  project_pcl_list: state => state.projects.project_pcl_list,
  slip_status_filters: state => state.projects.slip_status_filters,
  qa_status_filters: state => state.projects.qa_status_filters,
  slip_slip_filters: state => state.projects.slip_slip_filters,
  slip_assigned_to_filters: state => state.projects.slip_assigned_to_filters,
  span_list: state => state.projects.span_list,
  // qa
  qa_list: state => state.qa.qa_list,
  qa_mcl_list: state => state.qa.qa_mcl_list,
  qa_mcl_current_page: state => state.qa.qa_mcl_current_page,
  qa_mcl_page_size: state => state.qa.qa_mcl_page_size,
  qa_mcl_page_count: state => state.qa.qa_mcl_page_count,
  qa_mcl_count: state => state.qa.qa_mcl_count,
  qa_mcl_target_actual: state => state.qa.qa_mcl_target_actual,
  qa_pcl_target_actual: state => state.qa.qa_pcl_target_actual,
  qa_pcl_class1_list: state => state.qa.qa_pcl_class1_list,
  qa_pcl_class2_list: state => state.qa.qa_pcl_class2_list,
  qa_pcl_list: state => state.qa.qa_pcl_list,
  // query
  query_project_list: state => state.query.query_project_list,
  query_project_current_page: state => state.query.query_project_current_page,
  query_project_page_size: state => state.query.query_project_page_size,
  query_project_page_count: state => state.query.query_project_page_count,
  query_project_count: state => state.query.query_project_count,
  query_project_organization_id: state => state.query.query_project_organization_id,
  query_project_project_code: state => state.query.query_project_project_code,
  query_project_order_no: state => state.query.query_project_order_no
}
export default getters
